### Matrix Row Operations

In this section we show some basic row operations.

In [13]:
A = matrix(QQ, 3, [1,2,-1,0,1,3,2,-1,1])
show(A)

[ 1  2 -1]
[ 0  1  3]
[ 2 -1  1]

In [12]:
b = vector(QQ, [4,7,1])
show(b)

(4, 7, 1)

Let's check this matrix has a solution:

In [14]:
solution = A.solve_right(b)
show(solution)

(8/9, 7/3, 14/9)

### Augmented Matrices

We can create an augmented matrix by adding the constants vector ($b$) to the matrix of coefficients ($A$)

In [11]:
A_aug = A.augment(b, subdivide=True)
show(A_aug)

[ 1  2 -1| 4]
[ 0  1  3| 7]
[ 2 -1  1| 1]

### Reduced row echelon form (rref)

We show the method to retrieve the rref before showing row operations to manually obtain the rref.

In [10]:
rref = A_aug.rref()
show(rref)

[   1    0    0| 8/9]
[   0    1    0| 7/3]
[   0    0    1|14/9]

### Row operations

The three basic row operations are:

- Swap Rows
- Rescale Rows
- Add Multiple of Row

Let's start with the augmented matrix:

In [15]:
show(A_aug)

[ 1  2 -1| 4]
[ 0  1  3| 7]
[ 2 -1  1| 1]

In [16]:
# Row 3  <- Row 3 - 2*Row 1
A_aug.add_multiple_of_row(2, 0, -2)
show(A_aug)

[ 1  2 -1| 4]
[ 0  1  3| 7]
[ 0 -5  3|-7]

In [17]:
# Row 3 <-> Row 2
A_aug.swap_rows(1, 2)
show(A_aug)

[ 1  2 -1| 4]
[ 0 -5  3|-7]
[ 0  1  3| 7]

In [18]:
# Row 3 <- -5*Row 3
A_aug.rescale_row(2, -5)
show(A_aug)

[  1   2  -1|  4]
[  0  -5   3| -7]
[  0  -5 -15|-35]

... and so on

See if you can complete the operations to achieve reduce row echelon form (rref).

Each of these operations modify (mutate) the original matrix.  There are equivalent operations that leave the original matrix unchanged and return a new matrix.  These operations have _similar_ names, but have the prefix `with_`, e.g.

 - `swap_rows()` -> `with_swapped_rows()`
 - `rescale_row()` -> `with_rescaled_row()`
 - `add_multiple_of_row()` -> `with_added_multiple_of_row()`

The documentation for these (and many more) matrix operations can be found [here](https://doc.sagemath.org/html/en/reference/matrices/sage/matrix/matrix0.html).